### PR TITLE
Updated haml.js to the last version

### PR DESCRIPTION
**Pull request by ttp**
Looks like current version does not support

```
:else if
:else
```

Added configurable haml_path:

```
# config/application.rb
RubyHamlJs::Template.haml_path = "#{config.root}/vendor/assets/javascripts/haml.js"
```

### CODE REVIEW

**Comment by dnagir** [comment]
@ttp thanks for the PR. Could you please update the README RE haml_path and I'll merge & release it then.

**Comment by daviscabral** [comment]
Any update about merging this? :-) :+1:

**Comment by dnagir** [comment]
Didn't have time to add the new option to readme, thus no release yet.

**Comment by m3talsmith** [comment]
Last update 3 months ago ...?

**Comment by dnagir** [comment]
Merged and released.

**Comment by daviscabral** [comment]
I believe you need change the version (maybe 0.5?).

**Comment by dnagir** [comment]
@daviscabral why? The version was changed 1d2d971176c53982c2117d67a1305341d50cce95 to 0.0.4 after this PR got merged.

**Comment by daviscabral** [comment]
Sorry, my bad. I was still using the 0.3 version here.

**Pull request merged**
